AllCops:
  # Include gemspec and Rakefile
  Include:
    - 'lib/**/*.rb'
    - 'lib/**/*.rake'
    - 'spec/**/*.rb'
  Exclude:
    - 'bin/**/*'
    - 'Gemfile'
    - 'Rakefile'
    - '*.gemspec'
  DisplayCopNames: true
  StyleGuideCopsOnly: false
  TargetRubyVersion: 2.4

Style/AccessorMethodName:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/TrivialAccessors:
  Enabled: false

Style/Documentation:
  Exclude:
    - 'spec/**/*.rb'

Style/StringLiterals:
  Enabled: false

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*.rb'

Layout/SpaceInsideStringInterpolation:
  EnforcedStyle: no_space

Lint/AmbiguousRegexpLiteral:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Rails/Date:
  Enabled: false

Rails/TimeZone:
  Enabled: false
